from core.patch import Patch
from core.property import Pos_x, Pos_y, Shape_x, Shape_y


debug_patches_per_frame_0 = [
        [ # frame 0
            Patch('ball_a', {
                Pos_x: 4,
                Pos_y: 3,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_b', {
                Pos_x: 4,
                Pos_y: 1,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('wall_a', {
                Pos_x: 6,
                Pos_y: 2,
                Shape_x: 0,
                Shape_y: 3,
            }),
            Patch('wall_b', {
                Pos_x: 1,
                Pos_y: 2,
                Shape_x: 0,
                Shape_y: 3,
            }),
        ],
        [ # frame 1
            Patch('ball_a', {
                Pos_x: 3,
                Pos_y: 2,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_b', {
                Pos_x: 5,
                Pos_y: 2,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('wall_a', {
                Pos_x: 6,
                Pos_y: 2,
                Shape_x: 0,
                Shape_y: 3,
            }),
            Patch('wall_b', {
                Pos_x: 1,
                Pos_y: 2,
                Shape_x: 0,
                Shape_y: 3,
            }),
        ],
        [ # frame 2
            Patch('ball_a', {
                Pos_x: 2,
                Pos_y: 1,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_b', {
                Pos_x: 4,
                Pos_y: 3,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('wall_a', {
                Pos_x: 6,
                Pos_y: 2,
                Shape_x: 0,
                Shape_y: 3,
            }),
            Patch('wall_b', {
                Pos_x: 1,
                Pos_y: 2,
                Shape_x: 0,
                Shape_y: 3,
            }),
        ],
        [ # frame 3
            Patch('ball_a', {
                Pos_x: 3,
                Pos_y: 0,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_b', {
                Pos_x: 3,
                Pos_y: 4,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('wall_a', {
                Pos_x: 6,
                Pos_y: 2,
                Shape_x: 0,
                Shape_y: 3,
            }),
        ],
    ]


debug_patches_per_frame_1 = [
        [ # frame 0
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_1', {
                Pos_x: 12,
                Pos_y: 3,
                Shape_x: 2,
                Shape_y: 1,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 2,
                Pos_y: 10,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 10,
                Pos_y: 9,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 1
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_1', {
                Pos_x: 12,
                Pos_y: 3,
                Shape_x: 2,
                Shape_y: 1,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 3,
                Pos_y: 9,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 10,
                Pos_y: 9,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 2
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_1', {
                Pos_x: 12,
                Pos_y: 3,
                Shape_x: 2,
                Shape_y: 1,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 4,
                Pos_y: 8,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 9,
                Pos_y: 8,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 3
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_1', {
                Pos_x: 12,
                Pos_y: 3,
                Shape_x: 2,
                Shape_y: 1,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 5,
                Pos_y: 7,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 8,
                Pos_y: 7,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 4
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_1', {
                Pos_x: 12,
                Pos_y: 3,
                Shape_x: 2,
                Shape_y: 1,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 6,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 7,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 5
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_1', {
                Pos_x: 12,
                Pos_y: 3,
                Shape_x: 2,
                Shape_y: 1,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 5,
                Pos_y: 5,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 8,
                Pos_y: 5,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 6
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_1', {
                Pos_x: 12,
                Pos_y: 3,
                Shape_x: 2,
                Shape_y: 1,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 4,
                Pos_y: 4,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 9,
                Pos_y: 4,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 7
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 3,
                Pos_y: 3,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 8,
                Pos_y: 3,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 8
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 2,
                Pos_y: 2,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 7,
                Pos_y: 2,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 9
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 1,
                Pos_y: 1,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 6,
                Pos_y: 1,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 10
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 2,
                Pos_y: 2,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 5,
                Pos_y: 2,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 11
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 3,
                Pos_y: 3,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 4,
                Pos_y: 3,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 12
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 2,
                Pos_y: 4,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 5,
                Pos_y: 4,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 13
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 1,
                Pos_y: 5,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 6,
                Pos_y: 5,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 14
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 2,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 7,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 15
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 3,
                Pos_y: 7,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 8,
                Pos_y: 7,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 16
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 4,
                Pos_y: 8,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 9,
                Pos_y: 8,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 17
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 5,
                Pos_y: 9,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 10,
                Pos_y: 9,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 18
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 6,
                Pos_y: 10,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 11,
                Pos_y: 10,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 19
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 7,
                Pos_y: 11,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 12,
                Pos_y: 11,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 20
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 8,
                Pos_y: 10,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 13,
                Pos_y: 10,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 21
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 9,
                Pos_y: 9,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 14,
                Pos_y: 9,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 22
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_5', {
                Pos_x: 16,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 10,
                Pos_y: 8,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 15,
                Pos_y: 8,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 23
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 11,
                Pos_y: 7,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 14,
                Pos_y: 7,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 24
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 12,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 13,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 25
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 11,
                Pos_y: 5,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 14,
                Pos_y: 5,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 26
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 10,
                Pos_y: 4,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 15,
                Pos_y: 4,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 27
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 9,
                Pos_y: 3,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 16,
                Pos_y: 3,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 28
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 8,
                Pos_y: 2,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 17,
                Pos_y: 2,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 29
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 7,
                Pos_y: 1,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 16,
                Pos_y: 1,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 30
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 6,
                Pos_y: 2,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 15,
                Pos_y: 2,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
        [ # frame 31
            Patch('wall_1', {
                Pos_x: 0,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_2', {
                Pos_x: 22,
                Pos_y: 6,
                Shape_x: 0,
                Shape_y: 5,
            }),
            Patch('wall_3', {
                Pos_x: 11,
                Pos_y: 0,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('wall_4', {
                Pos_x: 11,
                Pos_y: 12,
                Shape_x: 10,
                Shape_y: 0,
            }),
            Patch('brick_2', {
                Pos_x: 19,
                Pos_y: 3,
                Shape_x: 1,
                Shape_y: 1,
            }),
            Patch('ball_1', {
                Pos_x: 5,
                Pos_y: 3,
                Shape_x: 0,
                Shape_y: 0,
            }),
            Patch('ball_2', {
                Pos_x: 14,
                Pos_y: 3,
                Shape_x: 0,
                Shape_y: 0,
            }),
        ],
    ]


debug_patches_per_frame = debug_patches_per_frame_1